# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the bin/rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: "Star Wars" }, { name: "Lord of the Rings" }])
#   Character.create(name: "Luke", movie: movies.first)

a1 = Avatar.create(name: "Heart Cake", image_url: "https://img.freepik.com/premium-vector/heart-shaped-cake-cartoon-vector_484148-480.jpg?w=996")
a2 = Avatar.create(name: "Cupcake", image_url: "https://img.freepik.com/premium-vector/cherry-cupcake-cartoon-vector-illustration_484148-139.jpg?w=996")
a3 = Avatar.create(name: "Icecream", image_url: "https://img.freepik.com/premium-vector/ice-cream-cone-three-layers-with-wafer-stick-cartoon-vector_484148-127.jpg?w=996")
a4 = Avatar.create(name: "Donut", image_url: "https://img.freepik.com/premium-vector/heart-shaped-donut-cartoon-vector_484148-474.jpg?w=996")
a5 = Avatar.create(name: "Latte", image_url: "https://img.freepik.com/premium-vector/coffe-with-cute-blue-cup-flat-cartoon-hand-drawn-vector-isolated_484148-96.jpg?w=996")
a6 = Avatar.create(name: "Croissant", image_url: "https://img.freepik.com/premium-vector/bakery-croissant-cartoon-vector-illustration_484148-134.jpg?w=996")
a7 = Avatar.create(name: "Bread", image_url: "https://img.freepik.com/premium-vector/sliced-white-bread-fly-flat-cartoon-hand-drawn-vector-isolated_484148-97.jpg")
a8 = Avatar.create(name: "Cake", image_url: "https://img.freepik.com/premium-vector/hand-drawn-birthday-cake-sliced-flat-cartoon-vector-isolated_484148-102.jpg?w=996")
a9 = Avatar.create(name: "Candy", image_url: "https://img.freepik.com/premium-vector/red-lollipop-cartoon-vector-illustration_484148-229.jpg?w=996")
a10 = Avatar.create(name: "Cookie", image_url: "https://img.freepik.com/premium-vector/heart-shaped-cookies-cartoon-vector_484148-481.jpg?w=996")

u1 = User.create(username: "chocolateluvr04", password: "1234", avatar: a8)
u2 = User.create(username: "mrsbaker", password: "1234", avatar: a6)
u3 = User.create(username: "clevverc00kie", password: "1234", avatar: a10)
u4 = User.create(username: "buttercup45", password: "1234", avatar: a2)
u5 = User.create(username: "bkrsdzn13", password: "1234", avatar: a4)

t1 = Tag.create(name: "Chocolate")
t2 = Tag.create(name: "Sweet")
t3 = Tag.create(name: "Savory")
t4 = Tag.create(name: "Pastry")
t5 = Tag.create(name: "Vegan")
t6 = Tag.create(name: "Dairy-Free")

# Original recipe by Ruth Source: https://www.allrecipes.com/recipe/25128/white-chip-chocolate-cookies/
r1 = Recipe.create(title: "White Chip Chocolate Cookies", image_url: "https://www.allrecipes.com/thmb/bd2oD68RsW0lch-pJI3_JiM1Bmw=/750x0/filters:no_upscale():max_bytes(150000):strip_icc():format(webp)/885180-3e35f23b3cb5457b93ab9954c5e036c0.jpg", is_private: false, user: u1)
i1 = Ingredient.create(name: "all-purpose flour", amount: 2, unit: "cups", ordinal: 0, recipe: r1)
i2 = Ingredient.create(name: "unsweetened cocoa powder", amount: 3/(4.to_f), unit: "cup", ordinal: 1, recipe: r1)
i3 = Ingredient.create(name: "baking soda", amount: 1, unit: "teaspoon", ordinal: 2, recipe: r1)
i4 = Ingredient.create(name: "salt", amount: 1/(2.to_f), unit: "teaspoon", ordinal: 3, recipe: r1)
i5 = Ingredient.create(name: "white sugar", amount: 2, unit: "cups", ordinal: 4, recipe: r1)
i6 = Ingredient.create(name: "unsalted butter", amount: 1, unit: "cup", ordinal: 5, recipe: r1)
i7 = Ingredient.create(name: "large eggs", amount: 2, unit: "each", ordinal: 6, recipe: r1)
i8 = Ingredient.create(name: "vanilla extract", amount: 2, unit: "teaspoons", ordinal: 7, recipe: r1)
i9 = Ingredient.create(name: "white chocolate chips", amount: 1 + 2/(3.to_f), unit: "cups", ordinal: 8, recipe: r1)
d1 = Direction.create(direction: "Preheat the oven to 350 degrees F (175 degrees C).", ordinal: 0, recipe: r1)
d2 = Direction.create(direction: "Combine flour, cocoa, baking soda, and salt in a bowl.", ordinal: 1, recipe: r1)
d3 = Direction.create(direction: "Beat sugar and butter with an electric mixer in a large bowl until smooth and creamy. Add eggs, one at a time, beating well after each addition. Stir in vanilla. Gradually mix in dry ingredients, then fold in white chocolate chips. Drop by spoonfuls onto ungreased baking sheets.", ordinal: 2, recipe: r1)
d4 = Direction.create(direction: "Bake in the preheated oven until set, 8 to 10 minutes. Remove from the oven, let cool on the baking sheets for 5 minutes, then transfer to a wire rack to cool completely.", ordinal: 3, recipe: r1)
d5 = Direction.create(direction: "", ordinal: 0, recipe: r1)
rt1 = RecipeTag.create(recipe: r1, tag: t1)
rt2 = RecipeTag.create(recipe: r1, tag: t2)

f1 = Favorite.create(recipe: r1, user: u2)
f2 = Favorite.create(recipe: r1, user: u3)
f3 = Favorite.create(recipe: r1, user: u4)
f4 = Favorite.create(recipe: r1, user: u5)

# Original recipe by Kathleen Amos-Robel Source: https://www.allrecipes.com/recipe/20366/dairy-free-chocolate-pudding/
r2 = Recipe.create(title: "Dairy-Free Chocolate Pudding", image_url: "https://www.allrecipes.com/thmb/hMJwLycOTvshVaafVh6hkUd0Yrc=/750x0/filters:no_upscale():max_bytes(150000):strip_icc():format(webp)/1067196-f7fa8ecf361f4621b790b92c5acd8526.jpg", is_private: false, user: u3)
i10 = Ingredient.create(name: "cornstarch", amount: 3, unit: "tablespoons", ordinal: 0, recipe: r2)
i11 = Ingredient.create(name: "water", amount: 2, unit: "tablespoons", ordinal: 1, recipe: r2)
i12 = Ingredient.create(name: "soy milk", amount: 1 + 1/(2.to_f), unit: "cups", ordinal: 2, recipe: r2)
i13 = Ingredient.create(name: "white sugar", amount: 1/(4.to_f), unit: "cup", ordinal: 3, recipe: r2)
i14 = Ingredient.create(name: "unsweetened cocoa powder", amount: 1/(4.to_f), unit: "cup", ordinal: 4, recipe: r2)
i15 = Ingredient.create(name: "vanilla extract", amount: 1/(4.to_f), unit: "teaspoon", ordinal: 5, recipe: r2)
d6 = Direction.create(direction: "Mix cornstarch and water together in a small bowl until a paste forms.", ordinal: 0, recipe: r2)
d7 = Direction.create(direction: "Combine soy milk, sugar, cocoa, and vanilla in a large saucepan; stir in cornstarch paste until well combined. Cook over medium heat, stirring constantly, until boiling. Continue to cook and stir until mixture thickens, 3 to 5 minutes.", ordinal: 1, recipe: r2)
d8 = Direction.create(direction: "Remove from the heat and let cool for 5 minutes; pudding will continue to thicken as it cools. Cover and refrigerate until completely cool, 1 to 2 hours.", ordinal: 2, recipe: r2)
rt3 = RecipeTag.create(recipe: r2, tag: t1)
rt4 = RecipeTag.create(recipe: r2, tag: t2)
rt5 = RecipeTag.create(recipe: r2, tag: t5)
rt6 = RecipeTag.create(recipe: r2, tag: t6)

f5 = Favorite.create(recipe: r2, user: u5)

# Original recipe by shaunawillman Source: https://www.allrecipes.com/recipe/241917/quick-cinnamon-rolls/
r3 = Recipe.create(title: "Quick Cinnamon Rolls", image_url: "https://www.allrecipes.com/thmb/nZcHUDoOoiPguYeVuvINBM_sLxQ=/0x512/filters:no_upscale():max_bytes(150000):strip_icc()/241917-quick-cinnamon-rolls-DDMFS-4x3-cec81ae72b1244d6ad9054eb46f0675b.jpg", is_private: false, user: u4)
i16 = Ingredient.create(name: "unsalted butter, melted, divided", amount: 3, unit: "tablespoons", ordinal: 0, recipe: r3)
i17 = Ingredient.create(name: "all-purpose flour", amount: 2, unit: "cups", ordinal: 1, recipe: r3)
i18 = Ingredient.create(name: "white sugar", amount: 2, unit: "tablespoons", ordinal: 2, recipe: r3)
i19 = Ingredient.create(name: "baking powder", amount: 2, unit: "teaspoons", ordinal: 3, recipe: r3)
i20 = Ingredient.create(name: "kosher salt", amount: 1, unit: "teaspoon", ordinal: 4, recipe: r3)
i21 = Ingredient.create(name: "unsalted butter, softened", amount: 3, unit: "tablespoons", ordinal: 5, recipe: r3)
i22 = Ingredient.create(name: "whole milk", amount: 2/(3.to_f), unit: "cup", ordinal: 6, recipe: r3)
i23 = Ingredient.create(name: "white sugar", amount: 1/(4.to_f), unit: "cup", ordinal: 7, recipe: r3)
i24 = Ingredient.create(name: "light brown sugar", amount: 1/(4.to_f), unit: "cup", ordinal: 8, recipe: r3)
i25 = Ingredient.create(name: "ground cinnamon", amount: 2, unit: "teaspoons", ordinal: 9, recipe: r3)
i26 = Ingredient.create(name: "confectioners' sugar", amount: 1, unit: "cup", ordinal: 10, recipe: r3)
i27 = Ingredient.create(name: "cream cheese, softened", amount: 4, unit: "ounces", ordinal: 11, recipe: r3)
i28 = Ingredient.create(name: "unsalted butter, softened", amount: 1/(4.to_f), unit: "cup", ordinal: 12, recipe: r3)
i29 = Ingredient.create(name: "vanilla extract", amount: 1/(2.to_f), unit: "teaspoon", ordinal: 13, recipe: r3)
d9 = Direction.create(direction: "Preheat the oven to 400 degrees F (200 degrees C). Brush an 8-inch square baking dish with 1 tablespoon of the melted butter.", ordinal: 0, recipe: r3)
d10 = Direction.create(direction: "To make the dough: Whisk flour, white sugar, baking powder, and salt together in a large bowl. Work 3 tablespoons softened butter into flour mixture using your hands until butter is lentil-sized.", ordinal: 1, recipe: r3)
d11 = Direction.create(direction: "Pour milk into flour-butter mixture and stir with a rubber spatula until a soft dough forms.", ordinal: 2, recipe: r3)
d12 = Direction.create(direction: "Turn dough out onto a well-floured work surface and roll dough into a 10- x 10-inch square. Brush surface of dough with remaining 2 tablespoons melted butter.", ordinal: 3, recipe: r3)
d13 = Direction.create(direction: "To make the filling: Whisk ¼ cup white sugar, brown sugar, and cinnamon together in a small bowl. Sprinkle 1 tablespoon cinnamon-sugar mixture in the bottom of the prepared baking dish. Sprinkle remaining cinnamon sugar over butter-brushed dough.", ordinal: 4, recipe: r3)
d14 = Direction.create(direction: "Roll dough around filling to form a log; cut log into 9 rolls about 1-inch wide; place rolls, cut-side up, in the prepared baking dish.", ordinal: 5, recipe: r3)
d15 = Direction.create(direction: "Bake in the preheated oven until rolls are puffed and lightly golden, 20 to 25 minutes.", ordinal: 6, recipe: r3)
d16 = Direction.create(direction: "To make the frosting: Beat confectioners' sugar, cream cheese, 1/4 cup softened butter, and vanilla extract together in a bowl until frosting is smooth.", ordinal: 7, recipe: r3)
d17 = Direction.create(direction: "Top hot cinnamon rolls with cream cheese frosting.", ordinal: 8, recipe: r3)
rt7 = RecipeTag.create(recipe: r3, tag: t2)
rt8 = RecipeTag.create(recipe: r3, tag: t4)

f6 = Favorite.create(recipe: r3, user: u1)
f7 = Favorite.create(recipe: r3, user: u2)
f8 = Favorite.create(recipe: r3, user: u5)
