# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the bin/rails db:seed command (or created alongside the database with db:setup).
#
# Examples:

a1 = Avatar.create(name: "Heart Cake", image_url: "https://img.freepik.com/premium-vector/heart-shaped-cake-cartoon-vector_484148-480.jpg?w=996")
a2 = Avatar.create(name: "Cupcake", image_url: "https://img.freepik.com/premium-vector/cherry-cupcake-cartoon-vector-illustration_484148-139.jpg?w=996")
a3 = Avatar.create(name: "Icecream", image_url: "https://img.freepik.com/premium-vector/ice-cream-cone-three-layers-with-wafer-stick-cartoon-vector_484148-127.jpg?w=996")
a4 = Avatar.create(name: "Donut", image_url: "https://img.freepik.com/premium-vector/heart-shaped-donut-cartoon-vector_484148-474.jpg?w=996")
a5 = Avatar.create(name: "Latte", image_url: "https://img.freepik.com/premium-vector/coffe-with-cute-blue-cup-flat-cartoon-hand-drawn-vector-isolated_484148-96.jpg?w=996")
a6 = Avatar.create(name: "Croissant", image_url: "https://img.freepik.com/premium-vector/bakery-croissant-cartoon-vector-illustration_484148-134.jpg?w=996")
a7 = Avatar.create(name: "Bread", image_url: "https://img.freepik.com/premium-vector/sliced-white-bread-fly-flat-cartoon-hand-drawn-vector-isolated_484148-97.jpg")
a8 = Avatar.create(name: "Cake", image_url: "https://img.freepik.com/premium-vector/hand-drawn-birthday-cake-sliced-flat-cartoon-vector-isolated_484148-102.jpg?w=996")
a9 = Avatar.create(name: "Candy", image_url: "https://img.freepik.com/premium-vector/red-lollipop-cartoon-vector-illustration_484148-229.jpg?w=996")
a10 = Avatar.create(name: "Cookie", image_url: "https://img.freepik.com/premium-vector/heart-shaped-cookies-cartoon-vector_484148-481.jpg?w=996")

u1 = User.create(username: "chocolateluvr04", password: "1234", avatar: a8)
u2 = User.create(username: "mrsbaker", password: "1234", avatar: a6)
u3 = User.create(username: "clevverc00kie", password: "1234", avatar: a10)
u4 = User.create(username: "buttercup45", password: "1234", avatar: a2)
u5 = User.create(username: "bkrsdzn13", password: "1234", avatar: a4)

# Original recipe by Ruth Source: https://www.allrecipes.com/recipe/25128/white-chip-chocolate-cookies/
r1 = Recipe.create(title: "White Chip Chocolate Cookies", image_url: "https://www.allrecipes.com/thmb/bd2oD68RsW0lch-pJI3_JiM1Bmw=/750x0/filters:no_upscale():max_bytes(150000):strip_icc():format(webp)/885180-3e35f23b3cb5457b93ab9954c5e036c0.jpg", is_private: false, user: u1)
i1 = Ingredient.create(name: "all-purpose flour", amount: 2, unit: "cups", ordinal: 0, recipe: r1)
i2 = Ingredient.create(name: "unsweetened cocoa powder", amount: "3/4", unit: "cup", ordinal: 1, recipe: r1)
i3 = Ingredient.create(name: "baking soda", amount: 1, unit: "teaspoon", ordinal: 2, recipe: r1)
i4 = Ingredient.create(name: "salt", amount: "1/2", unit: "teaspoon", ordinal: 3, recipe: r1)
i5 = Ingredient.create(name: "white sugar", amount: 2, unit: "cups", ordinal: 4, recipe: r1)
i6 = Ingredient.create(name: "unsalted butter", amount: 1, unit: "cup", ordinal: 5, recipe: r1)
i7 = Ingredient.create(name: "large eggs", amount: 2, unit: "each", ordinal: 6, recipe: r1)
i8 = Ingredient.create(name: "vanilla extract", amount: 2, unit: "teaspoons", ordinal: 7, recipe: r1)
i9 = Ingredient.create(name: "white chocolate chips", amount: "1 2/3", unit: "cups", ordinal: 8, recipe: r1)
d1 = Direction.create(direction: "Preheat the oven to 350 degrees F (175 degrees C).", ordinal: 0, recipe: r1)
d2 = Direction.create(direction: "Combine flour, cocoa, baking soda, and salt in a bowl.", ordinal: 1, recipe: r1)
d3 = Direction.create(direction: "Beat sugar and butter with an electric mixer in a large bowl until smooth and creamy. Add eggs, one at a time, beating well after each addition. Stir in vanilla. Gradually mix in dry ingredients, then fold in white chocolate chips. Drop by spoonfuls onto ungreased baking sheets.", ordinal: 2, recipe: r1)
d4 = Direction.create(direction: "Bake in the preheated oven until set, 8 to 10 minutes. Remove from the oven, let cool on the baking sheets for 5 minutes, then transfer to a wire rack to cool completely.", ordinal: 3, recipe: r1)
d5 = Direction.create(direction: "Enjoy!", ordinal: 4, recipe: r1)

f1 = Favorite.create(recipe: r1, user: u2)
f2 = Favorite.create(recipe: r1, user: u3)
f3 = Favorite.create(recipe: r1, user: u4)
f4 = Favorite.create(recipe: r1, user: u5)

# Original recipe by Kathleen Amos-Robel Source: https://www.allrecipes.com/recipe/20366/dairy-free-chocolate-pudding/
r2 = Recipe.create(title: "Dairy-Free Chocolate Pudding", image_url: "https://www.allrecipes.com/thmb/hMJwLycOTvshVaafVh6hkUd0Yrc=/750x0/filters:no_upscale():max_bytes(150000):strip_icc():format(webp)/1067196-f7fa8ecf361f4621b790b92c5acd8526.jpg", is_private: false, user: u2)
i10 = Ingredient.create(name: "cornstarch", amount: 3, unit: "tablespoons", ordinal: 0, recipe: r2)
i11 = Ingredient.create(name: "water", amount: 2, unit: "tablespoons", ordinal: 1, recipe: r2)
i12 = Ingredient.create(name: "soy milk", amount: "1 1/2", unit: "cups", ordinal: 2, recipe: r2)
i13 = Ingredient.create(name: "white sugar", amount: "1/4", unit: "cup", ordinal: 3, recipe: r2)
i14 = Ingredient.create(name: "unsweetened cocoa powder", amount: "1/4", unit: "cup", ordinal: 4, recipe: r2)
i15 = Ingredient.create(name: "vanilla extract", amount: "1/4", unit: "teaspoon", ordinal: 5, recipe: r2)
d6 = Direction.create(direction: "Mix cornstarch and water together in a small bowl until a paste forms.", ordinal: 0, recipe: r2)
d7 = Direction.create(direction: "Combine soy milk, sugar, cocoa, and vanilla in a large saucepan; stir in cornstarch paste until well combined. Cook over medium heat, stirring constantly, until boiling. Continue to cook and stir until mixture thickens, 3 to 5 minutes.", ordinal: 1, recipe: r2)
d8 = Direction.create(direction: "Remove from the heat and let cool for 5 minutes; pudding will continue to thicken as it cools. Cover and refrigerate until completely cool, 1 to 2 hours.", ordinal: 2, recipe: r2)

f5 = Favorite.create(recipe: r2, user: u5)

# Original recipe by shaunawillman Source: https://www.allrecipes.com/recipe/241917/quick-cinnamon-rolls/
r3 = Recipe.create(title: "Quick Cinnamon Rolls", image_url: "https://www.allrecipes.com/thmb/nZcHUDoOoiPguYeVuvINBM_sLxQ=/0x512/filters:no_upscale():max_bytes(150000):strip_icc()/241917-quick-cinnamon-rolls-DDMFS-4x3-cec81ae72b1244d6ad9054eb46f0675b.jpg", is_private: false, user: u3)
i16 = Ingredient.create(name: "unsalted butter, melted, divided", amount: 3, unit: "tablespoons", ordinal: 0, recipe: r3)
i17 = Ingredient.create(name: "all-purpose flour", amount: 2, unit: "cups", ordinal: 1, recipe: r3)
i18 = Ingredient.create(name: "white sugar", amount: 2, unit: "tablespoons", ordinal: 2, recipe: r3)
i19 = Ingredient.create(name: "baking powder", amount: 2, unit: "teaspoons", ordinal: 3, recipe: r3)
i20 = Ingredient.create(name: "kosher salt", amount: 1, unit: "teaspoon", ordinal: 4, recipe: r3)
i21 = Ingredient.create(name: "unsalted butter, softened", amount: 3, unit: "tablespoons", ordinal: 5, recipe: r3)
i22 = Ingredient.create(name: "whole milk", amount:" 2/3", unit: "cup", ordinal: 6, recipe: r3)
i23 = Ingredient.create(name: "white sugar", amount: "1/4", unit: "cup", ordinal: 7, recipe: r3)
i24 = Ingredient.create(name: "light brown sugar", amount: "1/4", unit: "cup", ordinal: 8, recipe: r3)
i25 = Ingredient.create(name: "ground cinnamon", amount: 2, unit: "teaspoons", ordinal: 9, recipe: r3)
i26 = Ingredient.create(name: "confectioners' sugar", amount: 1, unit: "cup", ordinal: 10, recipe: r3)
i27 = Ingredient.create(name: "cream cheese, softened", amount: 4, unit: "ounces", ordinal: 11, recipe: r3)
i28 = Ingredient.create(name: "unsalted butter, softened", amount: "1/4", unit: "cup", ordinal: 12, recipe: r3)
i29 = Ingredient.create(name: "vanilla extract", amount: "1/2", unit: "teaspoon", ordinal: 13, recipe: r3)
d9 = Direction.create(direction: "Preheat the oven to 400 degrees F (200 degrees C). Brush an 8-inch square baking dish with 1 tablespoon of the melted butter.", ordinal: 0, recipe: r3)
d10 = Direction.create(direction: "To make the dough: Whisk flour, white sugar, baking powder, and salt together in a large bowl. Work 3 tablespoons softened butter into flour mixture using your hands until butter is lentil-sized.", ordinal: 1, recipe: r3)
d11 = Direction.create(direction: "Pour milk into flour-butter mixture and stir with a rubber spatula until a soft dough forms.", ordinal: 2, recipe: r3)
d12 = Direction.create(direction: "Turn dough out onto a well-floured work surface and roll dough into a 10- x 10-inch square. Brush surface of dough with remaining 2 tablespoons melted butter.", ordinal: 3, recipe: r3)
d13 = Direction.create(direction: "To make the filling: Whisk ¼ cup white sugar, brown sugar, and cinnamon together in a small bowl. Sprinkle 1 tablespoon cinnamon-sugar mixture in the bottom of the prepared baking dish. Sprinkle remaining cinnamon sugar over butter-brushed dough.", ordinal: 4, recipe: r3)
d14 = Direction.create(direction: "Roll dough around filling to form a log; cut log into 9 rolls about 1-inch wide; place rolls, cut-side up, in the prepared baking dish.", ordinal: 5, recipe: r3)
d15 = Direction.create(direction: "Bake in the preheated oven until rolls are puffed and lightly golden, 20 to 25 minutes.", ordinal: 6, recipe: r3)
d16 = Direction.create(direction: "To make the frosting: Beat confectioners' sugar, cream cheese, 1/4 cup softened butter, and vanilla extract together in a bowl until frosting is smooth.", ordinal: 7, recipe: r3)
d17 = Direction.create(direction: "Top hot cinnamon rolls with cream cheese frosting.", ordinal: 8, recipe: r3)

f6 = Favorite.create(recipe: r3, user: u1)
f7 = Favorite.create(recipe: r3, user: u2)
f8 = Favorite.create(recipe: r3, user: u5)

# Original recipe by John Mitzewich Source: https://www.allrecipes.com/recipe/244198/baked-apple-roses/
r4 = Recipe.create(title: "Baked Apple Roses", image_url: "https://imagesvc.meredithcorp.io/v3/mm/image?url=https%3A%2F%2Fstatic.onecms.io%2Fwp-content%2Fuploads%2Fsites%2F43%2F2022%2F06%2F14%2F5859987-baked-apple-roses-Ariel-Liberda-1x1-1.jpg&q=60&c=sc&orient=true&poi=auto&h=512", is_private: false, user: u4)
i30 = Ingredient.create(name: "red apple, cored and very thinly sliced", amount: 1, unit: "large", ordinal: 0, recipe: r4)
i31 = Ingredient.create(name: "white sugar", amount: "1/4", unit: "cup", ordinal: 1, recipe: r4)
i32 = Ingredient.create(name: "ground cinnamon", amount: 1, unit: "tablespoon", ordinal: 2, recipe: r4)
i33 = Ingredient.create(name: "frozen puff pastry, thawed", amount: 1, unit: "sheet", ordinal: 3, recipe: r4)
i34 = Ingredient.create(name: "melted butter", amount: "1/4", unit: "cup", ordinal: 4, recipe: r4)
i35 = Ingredient.create(name: "egg", amount: 1, unit: "large", ordinal: 5, recipe: r4)
i36 = Ingredient.create(name: "water", amount: 2, unit: "teaspoons", ordinal: 6, recipe: r4)
i37 = Ingredient.create(name: "confectioners' sugar (Optional)", amount: 1, unit: "teaspoon", ordinal: 7, recipe: r4)
d18 = Direction.create(direction: "Preheat the oven to 400 degrees F (200 degrees C). Adjust an oven rack to the middle position. Butter two (6 to 8-ounce) ramekins and dust with white sugar.", ordinal: 0, recipe: r4)
d19 = Direction.create(direction: "Place apple slices on a microwave-safe plate, overlapping slightly if necessary. Microwave on high until slices slightly soften, about 45 seconds. Cover the plate with plastic wrap and a kitchen towel.", ordinal: 1, recipe: r4)
d20 = Direction.create(direction: "Mix together sugar and cinnamon in a small bowl.", ordinal: 2, recipe: r4)
d21 = Direction.create(direction: "Roll puff pastry sheet to less than 1/8-inch thickness. Using a pizza cutter, cut two (3x12-inch) rectangles. Reserve remaining pieces for another use.", ordinal: 3, recipe: r4)
d22 = Direction.create(direction: "Spread melted butter over dough; sprinkle with a generous amount of cinnamon sugar. Place apple slices along one long edge of dough, about 1/4 inch beyond the edge, overlapping slices slightly. Fold the bottom half of dough over apple slices to form a long folder of dough with rounded edges of apple slices exposed.", ordinal: 4, recipe: r4)
d23 = Direction.create(direction: "Beat together egg and water in a small bowl. Brush surface of dough with egg wash. Sprinkle with cinnamon sugar.", ordinal: 5, recipe: r4)
d24 = Direction.create(direction: "Starting at one end, roll dough to form a rose-shaped pastry. Seal roll with end of dough strip. Transfer roses to the prepared ramekins. Sprinkle with cinnamon sugar.", ordinal: 6, recipe: r4)
d25 = Direction.create(direction: "Bake on the middle rack in the preheated oven until well browned, about 45 minutes. Use tongs to remove the ramekins to a baking sheet to cool for 5 to 10 minutes. Remove apple roses from the ramekins and finish cooling on a wire rack. Dust with confectioners' sugar before serving.", ordinal: 7, recipe: r4)

f9 = Favorite.create(recipe: r4, user: u1)
f10 = Favorite.create(recipe: r4, user: u2)
f11 = Favorite.create(recipe: r4, user: u3)
f12 = Favorite.create(recipe: r4, user: u5)

# Original recipe by Colleen Royal Source: https://www.allrecipes.com/recipe/23971/danish-kringle/
r5 = Recipe.create(title: "Danish Kringle", image_url: "https://www.allrecipes.com/thmb/lxhS5N-IqmdRUrf02VWSLfC3E9A=/750x0/filters:no_upscale():max_bytes(150000):strip_icc():format(webp)/1989517-danish-kringle-myoldasskitchen-4x3-1-d1e767af70fc4234b44b3ea79b7ce969.jpg", is_private: false, user: u5)
i38 = Ingredient.create(name: "all-purpose flour, plus more as needed", amount: 2, unit: "cups", ordinal: 0, recipe: r5)
i39 = Ingredient.create(name: "salt", amount: "1/4", unit: "teaspoons", ordinal: 1, recipe: r5)
i40 = Ingredient.create(name: "cold butter, cubed", amount: 1, unit: "cup", ordinal: 2, recipe: r5)
i41 = Ingredient.create(name: "sour cream", amount: 1, unit: "cup", ordinal: 3, recipe: r5)
i42 = Ingredient.create(name: "egg", amount: 1, unit: "large", ordinal: 4, recipe: r5)
i43 = Ingredient.create(name: "cream cheese, softened", amount: 8, unit: "ounces", ordinal: 5, recipe: r5)
i44 = Ingredient.create(name: "brown sugar", amount: "1/4", unit: "cup", ordinal: 6, recipe: r5)
i45 = Ingredient.create(name: "ground cinnamon", amount: "1/2", unit: "teaspoon", ordinal: 7, recipe: r5)
i46 = Ingredient.create(name: "chopped English walnuts, toasted, divided", amount: 1 + 1/4, unit: "cups", ordinal: 7, recipe: r5)
i47 = Ingredient.create(name: "confectioners' sugar", amount: 1, unit: "cup", ordinal: 7, recipe: r5)
i48 = Ingredient.create(name: "water, or as needed", amount: 2, unit: "tablespoons", ordinal: 7, recipe: r5)
d26 = Direction.create(direction: "To make the pastry: Place flour and salt in a food processor and pulse to combine. Add butter and pulse until pieces are pea-sized. Add sour cream and pulse to form a sticky dough. Cover dough tightly with plastic wrap and refrigerate for 8 hours, or overnight.", ordinal: 0, recipe: r5)
d27 = Direction.create(direction: "Preheat the oven to 375 degrees F (190 degrees C). Line a large baking sheet with parchment paper.", ordinal: 1, recipe: r5)
d28 = Direction.create(direction: "To make the filling: Place egg yolk in a medium bowl; set egg white aside for egg wash. Add cream cheese, brown sugar, and cinnamon; beat with an electric mixer until smooth. Stir in 1 cup toasted walnuts until well combined.", ordinal: 2, recipe: r5)
d29 = Direction.create(direction: "Divide chilled dough in half. Roll each piece of dough into a 10x12-inch rectangle on a lightly floured surface. Working from a short side, spoon 1/2 of the filling along the center four inches of each rectangle. On both sides of the filling, cut the unfilled pastry into eight horizontal strips. Working top to bottom, fold each strip over the filling, alternating sides. Press to seal ends and tuck under; arrange braids on the prepared baking sheet.", ordinal: 3, recipe: r5)
d30 = Direction.create(direction: "Beat egg white and 1 tablespoon water together until smooth; brush evenly over each braid.", ordinal: 4, recipe: r5)
d31 = Direction.create(direction: "Bake kringles in the preheated oven until golden brown, about 30 to 35 minutes. Cool on the baking sheet for 30 minutes.", ordinal: 5, recipe: r5)
d32 = Direction.create(direction: "While pastries are cooling, make glaze: Mix together confectioners' sugar and 2 tablespoons water in a small bowl until smooth and thin enough to drizzle. Spoon or drizzle glaze over cooled pastries; sprinkle with remaining 1/4 cup of walnuts.", ordinal: 6, recipe: r5)

f13 = Favorite.create(recipe: r5, user: u1)
f14 = Favorite.create(recipe: r5, user: u2)
f15 = Favorite.create(recipe: r5, user: u3)
f16 = Favorite.create(recipe: r5, user: u4)

# Original recipe by Shelley Albeluhn Source: https://www.allrecipes.com/recipe/20144/banana-banana-bread/
r6 = Recipe.create(title: "Banana Banana Bread", image_url: "https://imagesvc.meredithcorp.io/v3/mm/image?url=https%3A%2F%2Fstatic.onecms.io%2Fwp-content%2Fuploads%2Fsites%2F43%2F2022%2F03%2F30%2F20144-banana-banana-bread-mfs-60.jpg&q=60&c=sc&orient=true&poi=auto&h=512", is_private: false, user: u1)
i49 = Ingredient.create(name: "all-purpose flour", amount: 2, unit: "cups", ordinal: 0, recipe: r6)
i50 = Ingredient.create(name: "baking soda", amount: 1, unit: "teaspoon", ordinal: 1, recipe: r6)
i51 = Ingredient.create(name: "salt", amount: "1/4", unit: "teaspoon", ordinal: 2, recipe: r6)
i52 = Ingredient.create(name: "brown sugar", amount: "3/4", unit: "cup", ordinal: 3, recipe: r6)
i53 = Ingredient.create(name: "butter", amount: "1/2", unit: "cup", ordinal: 4, recipe: r6)
i54 = Ingredient.create(name: "eggs, beaten", amount: 2, unit: "large", ordinal: 5, recipe: r6)
i55 = Ingredient.create(name: "mashed overripe bananas", amount: "2 1/3", unit: "cups", ordinal: 6, recipe: r6)
d33 = Direction.create(direction: "Preheat the oven to 350 degrees F (175 degrees C). Lightly grease a 9x5-inch loaf pan.", ordinal: 0, recipe: r6)
d34 = Direction.create(direction: "Combine flour, baking soda, and salt in a large bowl. Beat brown sugar and butter with an electric mixer in a separate large bowl until smooth. Stir in eggs and mashed bananas until well blended. Stir banana mixture into flour mixture until just combined. Pour batter into the prepared loaf pan.", ordinal: 1, recipe: r6)
d35 = Direction.create(direction: "Bake in the preheated oven until a toothpick inserted into the center comes out clean, about 60 minutes. Let bread cool in pan for 10 minutes, then turn out onto a wire rack to cool completely.", ordinal: 2, recipe: r6)

f17 = Favorite.create(recipe: r6, user: u2)
f18 = Favorite.create(recipe: r6, user: u3)
f19 = Favorite.create(recipe: r6, user: u4)

# Original recipe by Chadwick Boyd Source: https://www.allrecipes.com/herby-ricotta-biscuits-recipe-8347357
r7 = Recipe.create(title: "Herby Ricotta Biscuits", image_url: "https://www.allrecipes.com/thmb/ZtMvdWFxjkZuuN2NzURSVoxxGa0=/750x0/filters:no_upscale():max_bytes(150000):strip_icc():format(webp)/8347357-Herby-Ricotta-Biscuits-AR1424-4x3-82d4d9db5c1249c8ae4c62f0da64dfc1.jpg", is_private: false, user: u2)
i56 = Ingredient.create(name: "all-purpose flour", amount: "2 1/4", unit: "cups", ordinal: 0, recipe: r7)
i57 = Ingredient.create(name: "baking powder", amount: 1, unit: "tablespoon", ordinal: 1, recipe: r7)
i58 = Ingredient.create(name: "baking soda", amount: 1, unit: "teaspoon", ordinal: 2, recipe: r7)
i59 = Ingredient.create(name: "sea salt", amount: 1, unit: "teaspoon", ordinal: 3, recipe: r7)
i60 = Ingredient.create(name: "very cold butter", amount: 8, unit: "tablespoons", ordinal: 4, recipe: r7)
i61 = Ingredient.create(name: "full-fat ricotta cheese", amount: "3/4", unit: "cup", ordinal: 5, recipe: r7)
i62 = Ingredient.create(name: "very cold water", amount: "1/2", unit: "cup", ordinal: 6, recipe: r7)
i63 = Ingredient.create(name: "finely chopped fresh herbs (such as parsley, chives, thyme, and/or oregano)", amount: "1/4", unit: "cup", ordinal: 7, recipe: r7)
i64 = Ingredient.create(name: "lemon zest", amount: "1/2", unit: "teaspoon", ordinal: 8, recipe: r7)
i65 = Ingredient.create(name: "melted butter", amount: "1/2", unit: "tablespoons", ordinal: 9, recipe: r7)
i66 = Ingredient.create(name: "grated Parmesan cheese", amount: 2, unit: "tablespoons", ordinal: 10, recipe: r7)
d36 = Direction.create(direction: "Preheat oven to 425 degrees F (220 degrees C). Line a large baking sheet with parchment paper. Whisk together flour, baking powder, baking soda, and fine sea salt in a large bowl.", ordinal: 0, recipe: r7)
d37 = Direction.create(direction: "Coat whole stick of butter in flour mixture. Grate butter on the large holes of a box grater into bowl. (If butter starts to melt, coat butter in flour mixture again and continue grating.) Use your fingers to toss butter in flour mixture until all butter pieces are separated and coated in flour. Mixture should resemble coarse crumbs.", ordinal: 1, recipe: r7)
d38 = Direction.create(direction: "Whisk together ricotta  and water in a small bowl; add to flour mixture. Gently fold to bring dough together. Dough should be moistened but still crumbly. If dough is too dry, add more cold water, 1 tablespoon at a time, until fully moistened.", ordinal: 2, recipe: r7)
d39 = Direction.create(direction: "Turn dough out onto a lightly floured work surface. Lightly knead three or four times until dough comes together. Sprinkle with flour; pat to 3/4-inch thickness. Cut dough into four equal portions. Stack portions, press down, and pat again to form a 3/4-inch-thick rectangle. Repeat process three times, adding flour as needed.", ordinal: 3, recipe: r7)
d40 = Direction.create(direction: "Press a 2 1/2- to 3-inch biscuit cutter straight down into dough to cut out biscuits. Gently knead scraps together, pat to 3/4-inch thickness, and repeat cutting. Arrange on prepared baking sheet (biscuits should be barely touching).", ordinal: 4, recipe: r7)
d41 = Direction.create(direction: "Bake in the preheated oven until tops are crisp and golden brown, 15 to 16 minutes. Let cool on baking sheet 5 minutes.", ordinal: 5, recipe: r7)
d42 = Direction.create(direction: "Stir together fresh herbs and lemon zest in a small bowl. Brush tops of baked biscuits with melted butter; sprinkle with herb mixture and Parmesan cheese. (Store in an airtight container up to 3 days; chill up to 1 week. To reheat, bake about 10 minutes at 375 degrees F (190 degrees C).", ordinal: 6, recipe: r7)

f20 = Favorite.create(recipe: r7, user: u5)
f21 = Favorite.create(recipe: r7, user: u3)

# Original recipe by Pam Lolley Source: https://www.allrecipes.com/recipe/8450316/rhubarb-scones/
r8 = Recipe.create(title: "Rhubarb Scones", image_url: "https://www.allrecipes.com/thmb/0_vm-zFrD17R_u6JArVsgeaU-w0=/750x0/filters:no_upscale():max_bytes(150000):strip_icc():format(webp)/4Rhubarb-Scones-2000-6d8f178298c04fd5ac60b5db0ff64ca8.jpg", is_private: false, user: u3)
i67 = Ingredient.create(name: "all-purpose flour", amount: 2, unit: "cups", ordinal: 0, recipe: r8)
i68 = Ingredient.create(name: "white sugar", amount: "1/2", unit: "cup", ordinal: 1, recipe: r8)
i69 = Ingredient.create(name: "baking powder", amount: 1, unit: "tablespoon", ordinal: 2, recipe: r8)
i70 = Ingredient.create(name: "kosher salt", amount: "1/2", unit: "teaspoon", ordinal: 3, recipe: r8)
i71 = Ingredient.create(name: "ground cinnamon", amount: "1/2", unit: "teaspoon", ordinal: 4, recipe: r8)
i72 = Ingredient.create(name: "ground nutmeg", amount: "1/8", unit: "teaspoon", ordinal: 5, recipe: r8)
i73 = Ingredient.create(name: "cold unsalted butter, cut into 1/2-inch cubes", amount: "1/2", unit: "cup", ordinal: 6, recipe: r8)
i74 = Ingredient.create(name: "frozen chopped rhubarb", amount: 1, unit: "cup", ordinal: 7, recipe: r8)
i75 = Ingredient.create(name: "heavy whipping cream", amount: 1, unit: "cup", ordinal: 8, recipe: r8)
i76 = Ingredient.create(name: "vanilla extract", amount: 1, unit: "teaspoon", ordinal: 9, recipe: r8)
i77 = Ingredient.create(name: "grated orange zest, divided", amount: "1 1/2", unit: "teaspoons", ordinal: 10, recipe: r8)
i78 = Ingredient.create(name: "heavy whipping cream", amount: 2, unit: "tablespoons", ordinal: 11, recipe: r8)
i79 = Ingredient.create(name: "turbinado sugar", amount: 2, unit: "tablespoons", ordinal: 12, recipe: r8)
i80 = Ingredient.create(name: "powdered sugar", amount: "1/2", unit: "cup", ordinal: 13, recipe: r8)
i81 = Ingredient.create(name: "fresh orange juice", amount: 1, unit: "tablespoon", ordinal: 14, recipe: r8)
i82 = Ingredient.create(name: "kosher salt", amount: 1, unit: "pinch", ordinal: 15, recipe: r8)
d43 = Direction.create(direction: "Preheat the oven to 400 degrees F (200 degrees C). Line a baking sheet with parchment paper.", ordinal: 0, recipe: r8)
d44 = Direction.create(direction: "Whisk together flour, white sugar, baking powder, salt, cinnamon, and nutmeg in a large bowl. Cut butter into flour mixture with a pastry blender until crumbly and mixture resembles small peas. Freeze for 10 minutes.", ordinal: 1, recipe: r8)
d45 = Direction.create(direction: "Fold frozen rhubarb into flour mixture. Whisk together 1 cup heavy cream, vanilla, and 1 teaspoon orange zest in a glass measuring cup. Make a well in center of flour mixture and pour cream mixture into well; stir just until dry ingredients are moistened (do not overwork the dough).", ordinal: 2, recipe: r8)
d46 = Direction.create(direction: "Turn the dough out onto a lightly floured surface. Gently press dough into an 8-inch round circle.", ordinal: 3, recipe: r8)
d47 = Direction.create(direction: "Cut the round into 8 wedges using a sharp knife. Place the scones 2 inches apart on the prepared baking sheet.", ordinal: 4, recipe: r8)
d48 = Direction.create(direction: "Brush scones with remaining 2 tablespoons heavy cream and sprinkle with turbinado sugar.", ordinal: 5, recipe: r8)
d49 = Direction.create(direction: "Bake in the preheated oven until golden brown, 15 to 20 minutes. Cool on a wire rack for 10 minutes.", ordinal: 6, recipe: r8)
d50 = Direction.create(direction: "Whisk together powdered sugar, remaining 1/2 teaspoon orange zest, 1 tablespoon orange juice, and a pinch of kosher salt. Add up to 1/2 tablespoon more orange juice 1/2 teaspoon at a time, if needed, to reach desired consistency. Drizzle glaze over warm scones and serve immediately.", ordinal: 7, recipe: r8)

f22 = Favorite.create(recipe: r8, user: u5)
f23 = Favorite.create(recipe: r8, user: u1)
f24 = Favorite.create(recipe: r8, user: u2)
f25 = Favorite.create(recipe: r8, user: u4)

# Original recipe by Colleen Weeden Source: https://www.allrecipes.com/recipe/8535610/samoa-cookie-bars/
r9 = Recipe.create(title: "Samoa Cookie Bars", image_url: "https://imagesvc.meredithcorp.io/v3/mm/image?url=https%3A%2F%2Fstatic.onecms.io%2Fwp-content%2Fuploads%2Fsites%2F43%2F2023%2F02%2F15%2F8535610-Samoa-Cookie-Bars-1x1-1.jpg&q=60&c=sc&orient=true&poi=auto&h=512", is_private: false, user: u4)
i83 = Ingredient.create(name: "flour", amount: "1 1/2", unit: "cups", ordinal: 0, recipe: r9)
i84 = Ingredient.create(name: "cornstarch", amount: 1, unit: "tablespoon", ordinal: 1, recipe: r9)
i85 = Ingredient.create(name: "baking powder", amount: "1/2", unit: "teaspoon", ordinal: 2, recipe: r9)
i86 = Ingredient.create(name: "salt", amount: "1/2", unit: "teaspoon", ordinal: 3, recipe: r9)
i87 = Ingredient.create(name: "butter, softened", amount: "1/2", unit: "cup", ordinal: 4, recipe: r9)
i88 = Ingredient.create(name: "white sugar", amount: "1/4", unit: "cup", ordinal: 5, recipe: r9)
i89 = Ingredient.create(name: "packed brown sugar", amount: "1/4", unit: "cup", ordinal: 6, recipe: r9)
i90 = Ingredient.create(name: "egg yolk", amount: 1, unit: "large", ordinal: 7, recipe: r9)
i91 = Ingredient.create(name: "vanilla extract", amount: 1, unit: "teaspoon", ordinal: 8, recipe: r9)
i92 = Ingredient.create(name: "dulce de leche", amount: 13.4, unit: "ounce", ordinal: 9, recipe: r9)
i93 = Ingredient.create(name: "milk", amount: 3, unit: "tablespoons", ordinal: 10, recipe: r9)
i94 = Ingredient.create(name: "sweetened flaked coconut", amount: 14, unit: "ounces", ordinal: 11, recipe: r9)
i95 = Ingredient.create(name: "semisweet chocolate chips, divided", amount: 12, unit: "ounces", ordinal: 12, recipe: r9)
d51 = Direction.create(direction: "Preheat the oven to 350 degrees F (175 degrees C). Line a 9x13-inch baking pan with foil, extending foil over edges. Coat foil with cooking spray.", ordinal: 0, recipe: r9)
d52 = Direction.create(direction: "For crust, stir together flour, cornstarch, baking powder, and salt in a small bowl.", ordinal: 1, recipe: r9)
d53 = Direction.create(direction: "Beat butter in a large bowl with an electric mixer at medium speed for 30 seconds. Add both sugars and beat until light and fluffy at medium-high speed. Beat in egg yolk and vanilla extract. Beat in flour mixture (mixture will be crumbly). Press dough onto the bottom of the prepared pan.", ordinal: 2, recipe: r9)
d54 = Direction.create(direction: "Bake crust in the preheated oven until edges are light brown, 10 to 12 minutes.", ordinal: 3, recipe: r9)
d55 = Direction.create(direction: "Meanwhile, combine dulce de leche and milk in a medium bowl. Stir in flaked coconut.", ordinal: 4, recipe: r9)
d56 = Direction.create(direction: "Sprinkle 1 1/2 cups chocolate chips over the hot crust; let stand for 5 minutes until chocolate has melted. Spread melted chocolate over crust in an even layer. Carefully spread coconut mixture over chocolate layer. Return to the oven and bake 10 minutes more. Cool in the pan on a wire rack.", ordinal: 5, recipe: r9)
d57 = Direction.create(direction: "Microwave remaining chocolate chips in a small bowl, stirring once halfway through, until melted and smooth, 30 to 45 seconds. Drizzle melted chocolate over coconut mixture. Chill, covered, until set, about 1 hour. Using foil, lift out uncut cookies. Cut into bars.", ordinal: 6, recipe: r9)
f26 = Favorite.create(recipe: r9, user: u5)
f27 = Favorite.create(recipe: r9, user: u1)

# Original recipe by rosebud15404 Source: https://www.allrecipes.com/recipe/240565/cake-mix-cookies/
r10 = Recipe.create(title: "Red Velvet Cake Mix Cookies", image_url: "https://www.allrecipes.com/thmb/-9yXPrsHj71VbTDWlMVTJBhCvts=/750x0/filters:no_upscale():max_bytes(150000):strip_icc():format(webp)/9421360_RedVelvetCakeMixCookies4x3-d37105a7c64e4d7ea1f2c56ec6abd0c1.jpg", is_private: false, user: u5)
i96 = Ingredient.create(name: "red velvet cake mix", amount: 1, unit: "package", ordinal: 0, recipe: r10)
i97 = Ingredient.create(name: "eggs", amount: 2, unit: "large", ordinal: 1, recipe: r10)
i98 = Ingredient.create(name: "vegetable oil", amount: "1/2", unit: "cup", ordinal: 2, recipe: r10)
i99 = Ingredient.create(name: "chocolate chips", amount: "1/2", unit: "package (11 ounce)", ordinal: 3, recipe: r10)
d58 = Direction.create(direction: "Preheat the oven to 350 degrees F (175 degrees C).", ordinal: 0, recipe: r10)
d59 = Direction.create(direction: "Mix cake mix, eggs, and oil together in a bowl until well mixed; fold in chocolate chips. Roll dough into 24 balls and arrange on an ungreased baking sheet.", ordinal: 1, recipe: r10)
d60 = Direction.create(direction: "Bake in the preheated oven until lightly browned around the edges, 7 to 9 minutes.", ordinal: 2, recipe: r10)
d61 = Direction.create(direction: "Cool on the baking sheet 2 to 3 minutes before transferring to a wire rack to cool completely, 15 to 20 minutes.", ordinal: 3, recipe: r10)
f28 = Favorite.create(recipe: r10, user: u1)
f29 = Favorite.create(recipe: r10, user: u2)
f30 = Favorite.create(recipe: r10, user: u3)
f31 = Favorite.create(recipe: r10, user: u4)

# Original recipe by  Source: 
# r11 = Recipe.create(title: "", image_url: "", is_private: false, user: u3)
# i100 = Ingredient.create(name: "", amount: 2, unit: "tablespoons", ordinal: 10, recipe: r11)
# d61 = Direction.create(direction: "", ordinal: 0, recipe: r11)
# f32 = Favorite.create(recipe: r11, user: u5)